### ISSUE TITLE
Как этим пользоваться?

### ISSUE THREAD

**Issue by bnku** [kostyaz/DigisparkKeyboard_6K#1]
Привет. Стоит задача одновременного нажатия двух кнопок. Вижу метод `sendMultipleKeyPresses`, но его вызов никак не влияет на вывод:
```
byte keys[] = {KEY_W, KEY_D};
DigiKeyboard.sendMultipleKeyPresses(keys, 0);
```

Как заставить дигиспарк зажимать две кнопки?

**Comment by kostyaz** [comment]
Привет! Я использовал этот метод в [этом проекте](https://github.com/kostyaz/sun3-kbd-digispark/blob/87bd0b3305d44403945faa6beccc959db72c12ea/sun3/sun3.ino).

`keys[]` должен иметь фиксированную длину из 6.

Может так сработает?
```
byte keys[6] = {KEY_W, KEY_D};
DigiKeyboard.sendMultipleKeyPresses(keys, 0);
```

**Comment by bnku** [comment]
с указанием длины работает. Огрмное спасибо!
